name: Python Executable Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}


    steps:

    # Get current time
    - name: Get current time
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"``

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'
    
    - name: Install Python Dependencies
      run: python -m pip install pygame nuitka imageio grade
    
    - name: Run Nuitka Script
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        mode: app
        windows-icon-from-ico: icon.ico
        macos-app-icon: icon.ico
        disable-console: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flight-fight-nightly-build-${{ matrix.os }}-x64-${{ steps.date.outputs.date }}
        path: |
          build/*.exe
          build/*.bin
          build/*.app/**/*
